from __future__ import annotations

import fnmatch
import os
from functools import lru_cache
from pathlib import Path
import shutil
import glob

import yaml

from .models import RepoBundle, WorkspaceManifest

# Path to the override config file
_COPY_PY_OVERRIDES_PATH = Path(__file__).resolve().parent / "copy_py_overrides.yaml"


@lru_cache(maxsize=1)
def _load_copy_py_overrides() -> dict[str, list[str]]:
    """Load glob patterns for .py files that should be copied instead of generated."""
    if not _COPY_PY_OVERRIDES_PATH.exists():
        return {}
    with open(_COPY_PY_OVERRIDES_PATH, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data if isinstance(data, dict) else {}


def _copy_path(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.is_dir():
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst, ignore=shutil.ignore_patterns('__pycache__', '.pytest_cache', '.coverage'))
    else:
        shutil.copy2(src, dst)


def _expand_required_files(repo_dir: Path, patterns: list[str]) -> tuple[list[Path], list[str]]:
    copied: list[Path] = []
    missing: list[str] = []
    for item in patterns:
        matches = glob.glob(str(repo_dir / item))
        if not matches:
            missing.append(item)
            continue
        for m in matches:
            copied.append(Path(m))
    return copied, missing


def build_workspace(bundle: RepoBundle, workspace_dir: Path) -> WorkspaceManifest:
    """Copy evaluation and auxiliary files by allowlist, avoiding reference implementation leakage."""
    repo_dir = Path(bundle.repo_dir)
    cfg = bundle.config

    workspace_dir.mkdir(parents=True, exist_ok=True)

    copied: list[str] = []
    skipped: list[str] = []
    excluded_ref: list[str] = []

    allow_single = [
        cfg.get("check_tests"),
        cfg.get("dependencies"),
        cfg.get("setup_shell_script"),
    ]

    usage_examples = cfg.get("usage_examples")
    if isinstance(usage_examples, list):
        allow_single.extend(usage_examples)
    elif isinstance(usage_examples, str) and usage_examples.strip():
        allow_single.append(usage_examples)

    for rel in allow_single:
        if not rel:
            continue
        src = repo_dir / rel
        if not src.exists():
            skipped.append(rel)
            continue
        dst = workspace_dir / rel
        _copy_path(src, dst)
        copied.append(rel)

    required_files = cfg.get("required_files", [])
    if isinstance(required_files, list):
        paths, missing = _expand_required_files(repo_dir, required_files)
        for path in paths:
            rel = str(path.relative_to(repo_dir))
            _copy_path(path, workspace_dir / rel)
            copied.append(rel)
        skipped.extend(missing)

    # DevEval: input docs are individual fields (PRD, architecture_design, UML_class, UML_sequence)
    # Copy only input documents for generation
    for rel in [cfg.get("PRD"), cfg.get("architecture_design"), cfg.get("UML_class"), cfg.get("UML_sequence")]:
        if rel:
            src = repo_dir / rel
            if src.exists():
                _copy_path(src, workspace_dir / rel)
                copied.append(rel)

    # CodeProjectEval: UML uses a list field instead of individual fields
    uml_list = cfg.get("UML", [])
    if isinstance(uml_list, list):
        for rel in uml_list:
            if not rel:
                continue
            src = repo_dir / rel
            if src.exists():
                _copy_path(src, workspace_dir / rel)
                copied.append(rel)

    # CodeProjectEval: exclude source_code reference directory (reference implementation)
    source_code = cfg.get("source_code")
    if source_code:
        excluded_ref.append(source_code)
        skipped.append(source_code)
        # Create empty directory as generation target
        (workspace_dir / source_code).mkdir(parents=True, exist_ok=True)

    # Copy all non-.py files from the repo to ensure runtime data dependencies
    # (csv, txt, json, templates, locale, model files, etc.) are available.
    # .py files are excluded because they will be generated by the agent,
    # UNLESS they match an override pattern in copy_py_overrides.yaml.
    override_key = f"{bundle.dataset}/{bundle.repo}"
    override_patterns = _load_copy_py_overrides().get(override_key, [])
    for root, dirs, files in os.walk(repo_dir):
        # Skip __pycache__ and test dirs (tests are copied separately later)
        dirs[:] = [d for d in dirs if d not in ("__pycache__", ".pytest_cache", "unit_tests", "acceptance_tests")]
        for fname in files:
            # Skip coverage data files
            if fname == ".coverage" or fname.startswith(".coverage."):
                continue
            src = Path(root) / fname
            rel = str(src.relative_to(repo_dir))
            if src.suffix == ".py" or src.suffix == ".pyc":
                # Allow override: copy .py files matching configured patterns
                if not any(fnmatch.fnmatch(rel, pat) for pat in override_patterns):
                    continue
            dst = workspace_dir / rel
            if not dst.exists():
                _copy_path(src, dst)

    manifest = WorkspaceManifest(
        dataset=bundle.dataset,
        repo=bundle.repo,
        copied=sorted(set(copied)),
        skipped=sorted(set(skipped)),
        excluded_reference_paths=sorted(set(excluded_ref)),
    )
    return manifest


def copy_tests_for_final_eval(bundle: RepoBundle, workspace_dir: Path, config_key: str) -> str | None:
    """Copy the specified test directory (unit_tests / acceptance_tests) before final evaluation."""
    rel = bundle.config.get(config_key)
    if not rel:
        return None
    src = Path(bundle.repo_dir) / rel
    if not src.exists():
        return None
    _copy_path(src, workspace_dir / rel)
    return rel
